services:
  zap2xml:
    build: .
    restart: always
    volumes:
        - /xmltvdata:/data
    environment:
        - USERNAME=myemail@email.com
        - PASSWORD=**password**
        - OPT_ARGS=-I -D
        - XMLTV_FILENAME=xmltv.xml
